### ISSUE TITLE
Can't link if using main.cpp instead of main.c using default MakeFile

### ISSUE THREAD

**Issue by stratbasher** [BtheDestroyer/SpriteTools#6]
Hello!

I've made a main.cpp instead of main.c (I prefer using c++). Here's the code:

```
#include <3ds.h>
#include <spritetools.h>
#include <stdio.h>

int main(void) {
    
    ST_Init();
    
    ST_Fini();
    return 0;
}
```

Compiles fine if named "main.c", but when named "main.cpp", I get the following linker error:

```
linking RunAndGun.elf
main.o: In function `main':
c:/Dev/3ds/RunAndGun/source/main.cpp:7: undefined reference to `ST_Init()'
c:/Dev/3ds/RunAndGun/source/main.cpp:9: undefined reference to `ST_Fini()'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/c/Dev/3ds/RunAndGun/RunAndGun.elf] Error 1
make: *** [build] Error 2
====2 errors, 2 warnings====
```

I'm using the MakeFile shown in the example2.1.zip file.

**Comment by Bryce-Dixon** [comment]
I've never actually made 3DS homebrew with C++ just because I've never really needed any of its features. Because this is made for C (and I haven't added anything that really should be there to make it work with C++) you're going to need to modify some things. Here's a link that I found that should explain how to use C++ and C together: https://isocpp.org/wiki/faq/mixing-c-and-cpp

As for an official fix, I'll add a card to the Trello for adding C++ compatibility in the next update (whenever I have enough time away from school).

**Comment by Bryce-Dixon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add C++ support](https://trello.com/c/dpjfuVys/114-add-c-support)

**Comment by Bryce-Dixon** [comment]
Thanks to a contribution by [Substance12](https://github.com/Substance12) this feature should now be in the master branch. Download it from here: https://github.com/BtheDestroyer/SpriteTools/archive/master.zip
